---
- name:
  hosts: dev
  vars: 
    - pass.yaml
  tasks: 
  - name: Creating new group
    group: 
      name: dev
      state: present
  - name: Creating new user 
    user: 
      name: vedik 
      groups: dev 
      password: "{{ pw | password_hash('sha512') }}"
      update_password: always 
      state: present 
